label atsuko_ending_2:
    p "That's right! The refugee we once helped find a job in Liyue. She was the lucky one to escape Inazuma since the tight measures were enforced by the Inazuma Bakufu and Kanjobugyo."
    t "The last time we spoke to her, she was still accustoming to the Liyue culture."
    p "Paimon wonders if she's improved her Liyue manners."
    z "It is the first I'm hearing of this Atsuko person."
    t "She is this sweet girl that built her own raft to escape from Inazuma. She was planning on becoming a sailor but last time we left her with paperwork for Clerk Zhao."
    p "Mhm~ And back in her hometown, she was helping out in her family's store to deliver goods."
    z "Sounds like an innocent story to me."
    p "There is one problem though - Paimon doesn't remember Atsuko having a vision."
    t "Neither do I."
    p "What if she is a secret Inazuma spy sent here by the Bakufu to wreck Liyue from within?"
    t "That sounds a bit extreme - like a bad Snezhnayan folktale."
    z "As ridiculous as it sounds, we can't rule out the possibility. She might not be a vision bearer, but as an Inazuman, she might be helping someone else wreak havoc on the streets on Liyue."
    p "There's only one way to find out. Interrogation time!"
    z "Sure, if we can locate her. Would you happen to know where we could find her?"
    p "Isn't she always hanging around the docks, Traveler?"
    t "I think you're right, Paimon. It is the desire to find work as a sailor that keeps her there."
    z "Excellent. To the docks then?"
    p "To the docks!"

    scene bg harbor
    show paimon happy at left
    show ats small at center

    ats "Good fortune! Lovely seeing you around again, Traveler."
    t "Hey Atsuko. I see you are getting the hang of the local greetings."
    ats "I have been practicing. Working with locals has really helped me settle in Liyue."
    t "That's great to hear. So in working with the locals you must have made a few friends, haven't you?"
    ats "Well, I wouldn't say friends so much as acquaintances. But I'm getting by."
    t "And what about your friends from Inazuma? Anybody new in town?"
    ats "No, it's just me as far as I'm aware. Are you looking for anyone specific?"
    p "We are looking for someone, but we are not sure exactly who?"
    ats "Oh.. How so?"

    show zh happy at right with dissolve

    p "Atsuko, this is Zhongli. He is a friend of ours and he is helping us out with... um... a job."
    ats "Good fortune, Mr. Zhongli! Lovely meeting you today."
    z "The pleasure is all mine, Miss Atsuko. Tell me, are you aware of what's been happening on the streets of Liyue recently?"
    ats "I'm not sure what you're referring to, Mr. Zhongli. I usually spend my days either here by the docks or helping Clerk Zhao with some forms."
    z "I'm not talking about the days - I mean during the night-time."
    "{i}*Atsuko's eyes widen*{/i}"
    ats "Um... I don't go out much. Especially with the recent storms. I hear it's pretty scary outside."
    p "Ah yes, the storms. Funny how you should mention them. Surely you must have heard what happened during the storms - first to the Wanmin Restaurant, then to the Scent of Spring."
    ats "You mean... the... attacks?"
    z "Yes, the attacks. Do you know anything about them."
    ats "Um... I...."
    "{i}*Atsuko starts to shiver*{/i}"
    t "Is everything okay, Atsuko? You don't look well."
    ats "It's just... I've had some bad dreams during the storms."
    p "What do you mean {i}bad dreams{/i}?"
    ats "Every night there's a storm outside, I barely catch any sleep. I'm tormented by nightmares. Nightmares of all sorts of animals chasing me. But the really strange part is that there animals are made of stone."
    z "Where are those animals chasing you?"
    ats "On the streets of Liyue. I try to run away, but they keep on catching up to me. The first time they caught up to me was in front of the Wanmin Restaurant. They cornered me and I had nowhere to run."
    p "So how did you escape?"
    ats "I didn't. The pack of animals charged at me full speed. I closed my eyes and braced myself for the impact. I could hear them approaching closer and closer. But once they got to me I woke up screaming. Covered in cold sweat."
    p "That's awful! At least you got out of it safely."
    ats "I did, but I couldn't go back to sleep. So the next day I went to the office and I heard, that somebody had trashed the Wanmin Restaurant the night before. I thought it was a coincidence and I brushed it off."
    p "Yeah, a freaky coincidence."
    t "Paimon, stop interrupting the story. It's not polite."
    p "Sorry! Go on Atsuko. What happened next?"
    ats "Well there was nothing for a few days. Not until the next storm hit over Liyue. I had another restless night."
    p "More nightmares?"
    ats "Yes! I had a hard time falling asleep as it was. And once I fell asleep, the wild stone animals started chasing me again. This time down a different street."
    p "The street where the Scent of Spring is located?"
    ats "That's right. The animals cornered me in front of the Scent of Spring. Once again, I braced myself for the impact, closed my eyes and woke up screaming, covered in cold sweat."
    z "And we know what happened the next morning - the Scent of Spring was trashed."
    ats "Exactly! What are the odds of me {i}\"predicting\"{/i} the attacks twice in a row in my sleep?"
    t "I would say very close to non-existent."
    z "Miss Atsuko, if I may ask, has something changed drastically around you recently? When did you start having those nightmares?"
    "{i}*Atsuko crosses her arms and legs nervously*{/i}"

    ats "Like I said, it was the night of the first big storm recently. As far as a drastic change - not that I'm aware of. My daily routine is pretty mundane. It consists of work, walks, food and sleep. Although I think I might have caught someone's attention."
    t "Hmm? What makes you say that?"
    ats "Someone left this piece of jewelry at my place one day. I don't know what it is and I haven't really showed it to anyone. Still trying to figure out the sender first. Maybe you can help me?"

    "{i}*Atsuko pulls out an Inazuma Geo Vision*{/i}"

    p "Atsuko! That's a..."
    t "Paimon!!! Shhhh... keep it down, okay."
    p "But... But... That's... and... she..."
    ats "What? What is it?"
    "{i}*Paimon whispers softly*{/i}"
    p "it's a vision..."
    ats "A Vision?!"
    z "Yes, Miss Atsuko. It does look like you have indeed caught somebody's attention."
    ats "But... what? How? I... I don't understand? Why me?"
    z "I might be able to answer most of your questions. But I can't promise to answer them all."
    ats "How...?"
    z "There are several ways for an individual to obtain a Vision. The most common way is when an Archon deems an individual worthy, they may grant them a Vision."
    p "But that's an Inazuman Geo Vision. We know that the Electro Archon, that rules over Inazuma in trying to gather all the Visions for herself, not give them away."
    z "That's correct."
    p "And the Geo Archon could not have given her that Vision as well because he is {i}\"not around anymore\" after the event of the Rite of Parting{/i}."
    "{i}*Paimon winks at Zhongli*{/i}"
    p "So there is no way that this Vision came from one of them."
    z "That is also correct. Which rules out this way of obtaining the Vision. Another method is to rekindle a Masterless Vision. This happens when a deceased individual's Vision resonates with somebody new."
    p "Atsuko, when you got the Vision, was it empty? Like a blank rock in the middle? Or was it always orange with the Geo symbol?"
    ats "It was orange, as far as I recall."
    z "Which means only one thing - the Vision chose you. The Vision of a deceased person can also resonate with somebody close to the original Vision bearer."
    ats "This is someone else's Vision?"
    z "It was. Now it's yours."
    ats "But... that other person..."
    z "They are not around anymore. You have to carry on the Vision's legacy as its chosen one."
    ats "The Vision's chosen one? But why?"
    z "This question, I cannot answer. The reasons are beyond me. If we keep on exploring this narrative, we might get to the answer though."
    ats "I left Inazuma to be as far away as possible from Visions and the Electro Archon. I don't want to end up like the previous bearer of this Vision."
    p "Don't look at it negatively. Try to see it as a gift. A gift that you can controll."
    ats "But... I can't controll it. Oh no... Does that mean that I caused all the attacks? They weren't just dreams - they actually happened?"
    z "I suspect as much. But it's not your fault. You still don't know how to control and harness the powers of the Vision."
    ats "I can't control it. It seems like it is controlling me. I don't want to hurt people. Please... take it away from me."
    z "I'm afraid I can't do that. But I can do you one better - I have a Geo Vision of my own. How about I teach you how to use it?"
    ats "You want to teach me? I'm not sure that I can handle such power. What if I hurt someone on accident again?"
    p "You won't! Zhongli is a great teacher. Besides, the Traveler can also help."
    t "Yes, I can! I can also control the power of Geo. It is a bit simpler than conjuring mimics but it does the trick."
    ats "You three are willing to teach me how to control this... new power?"
    z "You can count on us, Miss Atsuko."
    p "Mhm~ And once your training is complete, maybe you can find sign up for the Adventurer's Guild."
    ats "Or join the Crux fleet and become a sailor."
    p "Or that. Whatever floats your boat!"
    ats "Alright then! But on one condition - we need to be far away from other people. I don't want anybody to get hurt accidentally!"
    t "You've got it. There's a nice hill on the outskirts of Liyue. Quite a few animals hang around there. Maybe we can go there and you can try and mimic them?"
    z "That sounds like a good first session. Lead the way, Traveler!"

    $ end_txt = "On the outskirts of Liyue Harbor..."
    call end_screen(end_txt)

    scene bg outskirts
    show paimon happy at left with dissolve
    show ats small at center with dissolve
    show zh happy at right with dissolve

    ats "Wow, Liyue Harbor looks so small from here."
    z "What a wonderful view. Traveler, how do you know about this spot?"
    t "Been here a few times. I've taken poets and painters here to find their muse."
    z "It truly is fascinating."
    p "Eh-em. We didn't come here for a picnic and inspiration. Atsuko could really use guidance in harnessing the power of Geo."
    t "Paimon's right. Let's get to work. We can enjoy the view when we take a break."
    z "Very well then. Miss Atsuko, could you show us that you can do so far?"
    ats "I... I can't do anything. All those times you say I conjured Geo animals, it seemed like it was out of my control. They were just there... chasing me."
    z "How did you feel in your dream?"
    ats "Scared. Terrified even. Similar to what I was feeling back home."
    p "Perhaps all those thunder and lightning reminded you of the wrath of the Electro Archon and triggered negative emotions from your past."
    ats "You could be right, Paimon. The nightmares happened during the stormy nights. Is that the way it's always going to be? I need to be scared for my life in order to control the powers within the Vision?"
    z "Not at all. Fear is a strong emotion. However, you could also tap into the Vision's powers with focus and concentration."
    ats "Focus and concentration? How do I do that?"
    z "Assuming that the powers you are manifesting are of the conjuration nature, you could focus on the object that you are trying to conjure. Picture it in your mind. Forget everything else for a moment."
    "{i}*Atsuko closes her eyes*{/i}"
    ats "Nothing's happening. Maybe I was not made for this."
    z "Nobody is {i}made{/i} for this. It just takes practice."
    p "How about we start small? In your dreams you conjured animals, right?"
    ats "That's right."
    p "You should start small then. See that bird over there. That's a Crimson Finch. Can you try and conjure one next to it?"
    ats "I can try..."
    "{i}*Atsuko closes her eyes again*{/i}"
    z "Focus on the finch. The head. The body. Two legs. Two wings. Now slowly open your eyes."
    "{i}*Atsuko conjures a Geo Mimic Finch next to the real one*{/i}"
    p "You did it! Way to go, Atsuko!"
    ats "I... I did it? I did it!"
    t "Impressive! See, you are a natural. You just needed the right guidance."
    ats "I did it. I can't believe it. I'm using the power of Geo at will."
    z "Very well done, Miss Atsuko."
    p "Now that you got the hang of it, Paimon thinks you are ready for a challenge. There's a squirrel jumping nearby. Do you see it? Right there by the pinecones."
    ats "I see it."
    z "We know that you are capable of conjuring a squirrel. Focus on it once again. Make room for the squirrel in your mind."
    "{i}*A Geo Mimic Squirrel appears next to the real one*{/i}"
    p "Success once again!"
    ats "This is getting easier with each try. Thank you, Mr. Zhongli, for guiding me."
    z "It's all you. Once you believe in yourself and learn the techniques, you can unlock your full potential."
    t "Yes, and I will make you a promise - I'll be there for you, when the rain starts to pour."
    ats "You are amazing, Traveler. I hope one day I will be able to wield the power of Geo like yourself."
    t "Patience and practice is the key."
    ats "How about some more practice just now? Hey, is that a boar in the distance?"
    z "Careful, you don't want to jump to larger animals too quickly. From the rubble left behind at the Scent of Spring we know that you can conjure a boar. But can you controll it?"
    ats "I believe I can! I want to give it a go!"
    z "Very well. This time, focus on the larger shapes first - the torso, the head, four legs, a pair of tusks..."
    "{i}*Atsuko conjures a Geo Mimic Boar right next to her*{/i}"
    z "Well done. Now take it easy and control the boar. Let it roam around a bit."
    p "She is doing pretty well for someone, who was scared of a vision just a few hours ago."
    t "I know. The Vision chose wisely with her."
    z "Steady. Steady. Don't go too fast with the boar."
    ats "Hmph~"
    z "Miss Atsuko, are you alright?"
    p "Looks like she is struggling."
    t "It seems that way. She is clenching her eyes. And her hands are shaking."
    z "Let me check on her."
    z "Miss Atsuko, can you hear me? Release the grip on the boar."
    t "Looks like she is in some sort of trance state."
    z "Miss Atsuko, snap out of it."
    p "Oh no, the Geo Mimic Boar is on the loose. And it's charging our way. Zhongli! Watch out!"

    $ globals()['menu_yalign'] = 0.7
    menu:
        p "{cps=0}Oh no, the Geo Mimic Boar is on the loose. And it's charging our way. Zhongli! Watch out!"

        "Push Zhongli away":
            show paimon with vpunch
            "{i}*The Traveler gets trampled by the Geo Mimic Boar*{/i}"
            jump demoralized
        "Cast Starfell Sword":
            t "Starfell Sword!"
            jump inspired

label demoralized:
    t "Argh... my back."
    ats "Huh! What happened? Traveler? Are you alright?"
    t "I'm fine, just a bit under stomped."
    ats "Oh no, did... did I do that? One second I was here, playing with the boar and the next... it's a blank."
    z "You pushed beyond the limits of your current powers. This is exactly what was happening in your dreams. You were afraid which caused you to unleash an immense amount of raw energy. This time, you were too relaxed and again released a bit more than you could handle."
    ats "I'm sorry, I didn't mean to do that. And now because of me, the Traveler is injured."
    t "I'll be fine, just need a few apples and perhaps a Sweet Madame."
    ats "No! This is unacceptable! Why did you make me think I'll be able to handle such powers? I don't want them! I don't want to hurt people!"
    p "Calm down, Atsuko. It was just an accident. With practice you will be able to master the power of your Vision."
    ats "Practice? How many accidents will occur in the process? How many people will I hurt unintentionally? How many business will I wreck before you realize this power is not mine to keep."
    t "Don't say that. This power is a gift..."
    ats "A gift? It feels more like a curse. I don't want anything to do with it. Ever again!"
    z "You can't just give up. We've made so much progress today. And there's always tomorrow. You will get the hang of it."
    ats "No I won't! I don't deserve this power! Leave me alone!"
    hide ats with dissolve
    p "Atsuko, wait!"
    z "Leave her be, Paimon. She is running back to Liyue Harbor to cool down. It takes practice and consistency to master the power of a Vision. She reached a bit too high today. But tomorrow will be different."
    p "Do you think so?"
    z "I know so."
    t "Well, that kind of wraps up our investigation. We know who was responsible for the \"attacks\" over Liyue."
    z "That's right, we do. But the Millelith still doesn't. We should keep it that way for now. Let Atsuko get a grip on her powers first. Then we will proceed with caution in introducing her to Lady Ningguang. I'm sure she will understand the delicate situation we are in."
    t "I hope she does. She must have walked that path when she got her Geo Vision."
    z "She did. And look at how powerful it made her."
    t "Well if this is the end of the investigation, I guess it's time to settle our debt."
    p "That's right. If Paimon remembers correctly you are due to have a nice dinner with us."
    t "How does Liuli Pavilion sound?"
    z "Sounds good to me. And after dinner, we can swing by and check up on Atsuko - see how she is holding up."
    p "Yay~ Liuli Pavilion, the best Tiansu meat in Liyue."

    $ end_txt = "After dinner at the Liuli Pavilion..."
    call end_screen(end_txt)

    "TBC"

label inspired:
    "INSPIRED"
