label in_front_of_guesthouse:
    scene bg guesthouse_night
    show paimon happy at right
    show zh happy at left
    t "Look at how dark the sky is... I didn't think we would make it in time!"
    z "And the wind has picked up significantly. It is going to be a heavy storm indeed. Are you going to be staying at the Baiju Guesthouse again?"
    t "Yes, I think it would be best. We can get a good night's sleep and pick up where we left off tomorrow morning."
    p "Paimon is not going anywhere before this thing passes. Even if it takes a week!"
    z "Relax, Paimon. It looks like the storm will be heavy but brief. There are a lot of dark clouds but if you look in the distance, you can see their end."
    t "So, Zhongli, are you thinking the storm will pass until the morning?"
    z "Certainly. Unless the wind changes direction and decides to keep the clouds around for longer. But that's highly unlikely."
    t "Okay so the original plan stands. We will meet up tomorrow morning in front of the Adventurers' Guild. Granted there is no rain in the morning, we can reconvene and resume the investigation?"
    z "You've got it! But I better get going before the rain starts. It looks like it could happen any moment now!"
    p "Okay... Hurry home, Zhongli. We'll see you tomorrow!"
    z "Be safe tonight! Both of you."
    p "B-bye~"
    $ end_txt = "The morning after..."
    call end_screen(end_txt)
    jump day_after_liyue

label day_after_liyue:
    # post guesthouse / post balloon
    scene bg adv_far
    show paimon happy at right
    if stayed_in_mondstadt:
        show zh happy at left
        z "Mmm~ there's no place like home."
        t "Yeah... you can say that again."
        z "Oh, I'm sorry, I didn't mean to upset you. I just meant it's good to be back in Liyue..."
        t "Don't worry, it's okay. I still have a lot to do here before going home anyway."
        p "Mhm~ and one of the things you need to do is bring this investigation to an end!"
        z "Paimon's right! We need to get more clues to keep us going."
        t "I know, but where do we find them? We've already looked at the crime scene twice and we've gotten all of the useful information out of it."
        z "Well, we eliminated all the suspects from Mondstadt but we've been away from Liyue for a few days now. Maybe there is some development within Liyue that we are not aware of."
        p "Zhongli, do you think we should ask the Millelith?"
        z "The Millelith might not be the best affiliation to ask. They have stricter protocols and might not be willing to give any information to us."
        p "Is there another central hub for information then?"
        t "How about the Adventurers' Guild?. All adventurers are required to check in with the Adventurers' Guild. Which means the coordinator will have a lot of information about events going around Liyue."
        z "You are absolutely right, Traveler!"
        p "And as members of the Adventurers' Guild, we can access that information. Especially if we are trying to eliminate a threat!"
        t "That's right! I see Lan, the branch master is around. We can go talk to her."
        z "Sounds good! Lead the way!"
        scene bg lan
        show paimon happy at center with dissolve
        show zh happy at right with dissolve
        p "Hey, Lan!"
        l "Well, well, well. What do we have here? Paimon, Traveler, you brought extra company."
        p "This is Zhongli, he is helping us with an investigation."
        l "Well, this is a nice search party you've got together. Unfortunately, I don't have any new leads regarding the Unseen Razor."
        p "We are not here for that commission this time. In fact, we are not after any commission. We were out of town for a few days and were wondering what the latest news were around here."
        l "Not sure when you left, but Liyue is in a pretty serious shock after the recent attacks."
        t "Attacks? As in plural?"
        l "Yes! It started with the Wanmin Restaurant a few days ago."
        p "We were here for that. We are trying to help Chef Mao catch the person responsible."
        l "Well, the Millelith is also on the job and has been for the past few days. Unfortunatly without any success. Seems like whoever trashed the restaurant is now targeting other small local businesses."
        t "Please, tell us more! We need as much information as possible!"
        l "I don't have any official reports but the latest news is that someone broke in the Scent of Spring a couple of nights ago. They damaged most of the goods inside. There's rocks and shattered perfume bottles everywhere."
        p "Uh-oh ... rocks you say..."
        l "Yeah, similar to the ones thrown in the Wanmin Restaurant. The Millelith have been restless. Increasing patrol duty. Investigating the whole situation. It's out of control."
        t "I think it's time to take matters in our hands once again!"
        z "Sounds like whoever struck once is not afraid to do it again. And in such a short time frame. And just a couple of streets away."
        t "At least we can be almost certain that whoever did that is still around. Maybe planning another attack? If we can figure out their pattern, maybe we can prevent the next one."
        l "The pattern so far is that it always happends in the middle of the night and there are always rocks of various shapes and sizes involved."
        z "Under the night's cover. That's smart. Lan, you said that it happened a couple of nights ago. Do you know which night exactly?"
        l "Yes, ofcourse. It was the night of the second big storm over Liyue. There've been only two recently."
        p "Heey~ the night before the attack of the Wanmin Restaurant was stormy as well, wasn't it?"
        l "Yes, that was the night of the first big storm."
        t "Paimon! You're right! The pattern begins to form. I wonder if the Millelith have connected the dots yet."
        l "They probably have. Their highest ranks are involved now."
        z "Now that we have a possible pattern for the timing, let's go and investigate the method of execution."
        t "Are you saying we should visit the crime scene?"
        z "Yes, and better get going fast! The Millelith might have already messed it up since it has been sitting there for a couple of days."
        p "Oh yes, yes, yes. Let's go look at some more weird rocks."
        t "Someone is eager."
        p "Eager to catch some bad guys! Now that we have more information, Paimon feels like it will be easier."
        z "Don't get your hopes up, Paimon. It could all be just a coincidence."
        p "There's no such thing as coincidences. It's a pattern!"
        z "If you say so... just don't want to see you disappointed if we hit another dead end."
        p "Not this time! Hurry, before the Millelith messes up the crime scene!"
        hide paimon happy with dissolve
        t "Thanks for the information, Lan. Once we are done with this investigation we will resume the search for the Unsees Razor. It is bound to pop up some place!"
        l "Thanks, Traveler. I hope you're right. And good luck with your current investigation!"
        t "Thanks!"
    else:
        p "Ughh~ Where is he?"
        t "Don't worry, Paimon. He will be here soon."
        p "It's not typical for Zhongli to be late."
        t "Come on, cut him some slack. The trip to Mondstadt must have brought back memories."
        p "Okay, okay~ but Paimon is eager to pick up the investigation. We are at a dead end... What's our next move?"
        t "We'll decide together, once Zhongli arrives. Until then, just try to enjoy the sun while it's out."
        p "I guess you've got a point. With so many storms recently, Paimon should be happy to floating in the sun."
        t "Hehe~ that's right. But don't get too comfortable. I see someone in the distance coming our way."
        p "Wait, who is it? Paimon can't see that far!"
        show paimon happy at center with move
        show zh happy at right with dissolve
        z "Good morning!"
        p "Oh.. if it isn't {i}Mr. I-can-show-up-whenever-I-want-to.{/i}"
        z "Sorry to keep you waiting this morning. I had some errands to run earlier."
        t "Don't mind Paimon. She is just grumpy because we are going nowhere with our investigation..."
        z "Ah, I see. Well, I'm here now. We can get back on it. Do you have any new information?"
        t "No, we haven't asked around yet. We were waiting for you since we are partners in this!"
        z "Oh, I'm flattered. But I'm just a consultant here. You are the lead investigators on this case."
        p "We might be, but Paimons list is pretty dry at this point. We need to find some new suspects!"
        t "Well, I can see Lan over there by the Adventurers' Guild. She is a very resourceful individual. How about asking her if there has been any progress within Liyue?"
        z "Excellent idea, Traveler. All adventurers report to the Adventurers' Guild daily. So if anyone has seen anything unusual, Lan would know!"
        p "Paimon's list is ready to be filled once again! Let's go talk to Lan!"
        scene bg lan
        show paimon happy at center with dissolve
        show zh happy at right with dissolve
        p "Hey, Lan!"
        l "Well, well, well. What do we have here? Paimon, Traveler, you brought extra company."
        p "This is Zhongli, he is helping us with an investigation."
        l "Well, this is a nice search party you've got together. Unfortunately, I don't have any new leads regarding the Unseen Razor."
        p "We are not here for that commission this time. In fact, we are not after any commission. We were out of town for a few days and were wondering what the latest news were around here."
        l "Not sure when you left, but Liyue is in a pretty serious shock after the recent attacks."
        t "Attacks? As in plural?"
        l "Yes! It started with the Wanmin Restaurant a few days ago."
        p "We were here for that. We are trying to help Chef Mao catch the person responsible."
        l "Well, the Millelith is also on the job and has been for the past few days. Unfortunatly without any success. Seems like whoever trashed the restaurant is now targeting other small local businesses."
        t "Please, tell us more! We need as much information as possible!"
        l "I don't have any official reports but the latest news is that someone broke in the Scent of Spring last night. They damaged most of the goods inside. There's rocks and shattered perfume bottles everywhere."
        p "Uh-oh ... rocks you say..."
        l "Yeah, similar to the ones thrown in the Wanmin Restaurant. The Millelith have been restless. Increasing patrol duty. Investigating the whole situation. It's out of control."
        t "I think it's time to take matters in our hands once again!"
        z "Sounds like whoever struck once is not afraid to do it again. And in such a short time frame. And just a couple of streets away."
        t "At least we can be almost certain that whoever did that is still around. Maybe planning another attack? If we can figure out their pattern, maybe we can prevent the next one."
        l "The pattern so far is that it always happends in the middle of the night and there are always rocks of various shapes and sizes involved."
        z "Under the night's cover. That's smart. Last night there was a storm as well, so the thunder and lightning could provide visual and audio distractions."
        p "Heey~ the night before the attack of the Wanmin Restaurant was stormy as well, wasn't it?"
        t "Paimon! You're right! The pattern begins to form. I wonder if the Millelith have connected the dots yet."
        l "They probably have. Their highest ranks are involved now."
        z "Now that we have a possible pattern for the timing, let's go and investigate the method of execution."
        t "Are you saying we should visit the crime scene?"
        z "Yes, and better get going fast, while it's fresh!"
        p "Oh yes, yes, yes. Let's go look at some more weird rocks."
        t "Someone is eager."
        p "Eager to catch some bad guys! Now that we have more information, Paimon feels like it will be easier."
        z "Don't get your hopes up, Paimon. It could all be just a coincidence."
        p "There's no such thing as coincidences. It's a pattern!"
        z "If you say so... just don't want to see you disappointed if we hit another dead end."
        p "Not this time! Hurry, before the Millelith messes up the crime scene!"
        hide paimon happy with dissolve
        t "Thanks for the information, Lan. Once we are done with this investigation we will resume the search for the Unsees Razor. It is bound to pop up some place!"
        l "Thanks, Traveler. I hope you're right. And good luck with your current investigation!"
        t "Thanks!"
